name: CertCentral Suspicious Signers List Update

on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:

jobs:
  fetch-CertCentral-Signer-List:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run CertCentral signer list downloader
        run: |
          cd Lists/CERTS
          python download_certcentral_suspicious_signers_list.py

      - name: Show resulting files
        run: ls -l Lists/CERTS

      - name: Commit and Push results
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull
          git add Lists/CERTS/certcentral_signers_list.csv
          git commit -m "Update CertCentral Suspicious Signers List" --allow-empty
          git push
