name: Proxy ProxyScrape Fetch

on:
  schedule:
    - cron: '10 */2 * * *'  # Runs every 2 hours
  workflow_dispatch:

jobs:
  fetch-proxyscrape-proxy-list:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests
      
      - name: Fetch proxy list
        run: |
          cd Lists/PROXY/proxyscrape.com
          python3 fetch_proxy_list.py

      - name: List updated files
        run: ls -lah Lists/PROXY/proxyscrape.com

      - name: Commit and Push results
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull
          git add Lists/PROXY/proxyscrape.com/*
          git commit -m "Update hourly ProxyScrape proxy list" --allow-empty
          git push
